# Backbone
backbone: resnet50

# Transfer loss related
transfer_loss_weight: 1.0
transfer_loss: coral

# Optimizer related
lr: 0.003
weight_decay: 0.0005
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9
